# Call TcpInstruments.init_tcp_yaml() after modifying this file

# Scope

SDS1204XE:
    alias: "SDSXE"
    address: "192.168.1.94:5025"
    
# MCU

Teensy4.1:
    alias: "Teensy:
    address: "192.1.1.1:5966"
